include: package:pedantic/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # These are for 2.5.0-dev.2.0 and after
    implicit_dynamic_function: ignore
    implicit_dynamic_list_literal: ignore
    implicit_dynamic_map_literal: ignore
    implicit_dynamic_parameter: ignore
    implicit_dynamic_variable: ignore
    # These are pre-2.5.0-dev.2.0
    strong_mode_implicit_dynamic_list_literal: ignore
    strong_mode_implicit_dynamic_map_literal: ignore
    strong_mode_implicit_dynamic_parameter: ignore
    strong_mode_implicit_dynamic_variable: ignore
linter:
  rules:
     # Errors
     - avoid_empty_else
     - comment_references
     - control_flow_in_finally
     - empty_statements
     - hash_and_equals
     - test_types_in_equals
     - throw_in_finally
     - unrelated_type_equality_checks
     - valid_regexps

     # Style
     - annotate_overrides
     - avoid_init_to_null
     - avoid_return_types_on_setters
     - await_only_futures
     - camel_case_types
     - empty_catches
     - empty_constructor_bodies
     - library_names
     - library_prefixes
     - non_constant_identifier_names
     - prefer_generic_function_type_aliases
     - prefer_is_not_empty
     - slash_for_doc_comments
     - type_init_formals
     - unnecessary_const
     - unnecessary_new
