name: mockito
version: 4.1.2-dev

description: A mock framework inspired by Mockito.
homepage: https://github.com/dart-lang/mockito

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  analyzer: ^0.38.0
  build: ^1.1.3
  code_builder: ^3.2.0
  collection: ^1.1.0
  dart_style: ^1.3.0
  matcher: ^0.12.3
  meta: ^1.0.4
  test_api: ^0.2.1

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.0
  build_web_compilers: '>=1.0.0 <3.0.0'
  pedantic: ^1.3.0
  test: ^1.5.1
