name: mockito
version: 1.0.1+1
authors:
  - Dmitriy Fibulwinter <fibulwinter@gmail.com>
  - Ted Sander <tsander@google.com>
  - Samuel Rawlins <srawlins@google.com>
  - Matan Lurey <matanl@google.com>
description: A mock framework inspired by Mockito.
homepage: https://github.com/fibulwinter/dart-mockito
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  meta: '>=1.0.4 <2.0.0'
  test: '>=0.12.0 <0.13.0'
