name: mockito
version: 2.0.0-dev
authors:
  - Dmitriy Fibulwinter <fibulwinter@gmail.com>
  - Dart Team <misc@dartlang.org>
description: A mock framework inspired by Mockito.
homepage: https://github.com/dart-lang/mockito
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  matcher: '^0.12.0'
  meta: '^1.0.4'
  test: '>=0.12.0 <0.13.0'
