name: mockito
version: 0.8.1
author: Dmitriy Fibulwinter <fibulwinter@gmail.com>
homepage: https://github.com/fibulwinter/dart-mockito
description: >
  A mock framework inspired by Mockito.
dependencies:
  matcher: ">=0.10.0 <1.0.0"
dev_dependencies:
  unittest: ">=0.11.0 <1.0.0"
environment:
  sdk: ">=1.0.0 <2.0.0"