name: mockito
version: 5.0.0-nullsafety.3

description: A mock framework inspired by Mockito.
homepage: https://github.com/dart-lang/mockito

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  analyzer: '>=0.39.15 <0.42.0'
  build: ^1.3.0
  code_builder: ^3.4.0
  collection: ^1.15.0-nullsafety.5
  dart_style: ^1.3.6
  matcher: ^0.12.10-nullsafety.3
  meta: ^1.3.0-nullsafety
  path: ^1.8.0-nullsafety.3
  source_gen: ^0.9.6
  test_api: ^0.2.19-nullsafety

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^1.1.0
  build_web_compilers: '>=1.0.0 <3.0.0'
  http: ^0.12.0
  package_config: ^1.9.3
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety.12
