name: mockito
version: 4.1.2-dev

description: A mock framework inspired by Mockito.
homepage: https://github.com/dart-lang/mockito

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ^0.39.11
  build: ^1.3.0
  code_builder: ^3.4.0
  collection: ^1.1.0
  dart_style: ^1.3.6
  matcher: ^0.12.3
  meta: '>=1.0.4 <1.2.0'
  test_api: ^0.2.1

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^1.1.0
  build_web_compilers: '>=1.0.0 <3.0.0'
  pedantic: '>=1.3.0 <1.9.1'
  test: ^1.5.1

dependency_overrides:
  build_resolvers: ^1.3.10
