name: mockito
version: 3.0.0-beta
authors:
  - Dmitriy Fibulwinter <fibulwinter@gmail.com>
  - Dart Team <misc@dartlang.org>
description: A mock framework inspired by Mockito.
homepage: https://github.com/dart-lang/mockito
environment:
  sdk: '>=2.0.0-dev.16.0 <2.0.0'

dependencies:
  collection: '^1.1.0'
  matcher: '^0.12.0'
  meta: '^1.0.4'
  test: '>=0.12.25 <0.13.0'

dev_dependencies:
  build_runner: ^0.7.11
  build_test: ^0.10.0
  build_web_compilers: ^0.3.1
