// Copyright (c) 2018, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'operating_system.dart';
import 'test_platform.dart';

/// The platform on which a test suite is loaded.
class SuitePlatform {
  /// The platform on which the suite is running.
  final TestPlatform platform;

  /// The operating system on which the suite is running.
  ///
  /// This will always be [OperatingSystem.none] if `platform.isBrowser` is
  /// true.
  final OperatingSystem os;

  /// Creates a new platform with the given [platform] and [os], which defaults
  /// to [OperatingSystem.none].
  ///
  /// Throws an [ArgumentError] if [platform] is a browser and [os] is not
  /// `null` or [OperatingSystem.none].
  SuitePlatform(this.platform, {OperatingSystem os})
      : os = os ?? OperatingSystem.none {
    if (platform.isBrowser && this.os != OperatingSystem.none) {
      throw new ArgumentError(
          'No OS should be passed for platform "$platform".');
    }
  }

  /// Converts a JSON-safe representation generated by [serialize] back into a
  /// [SuitePlatform].
  factory SuitePlatform.deserialize(Object serialized) {
    var map = serialized as Map;
    return new SuitePlatform(new TestPlatform.deserialize(map['platform']),
        os: OperatingSystem.find(map['os']));
  }

  /// Converts [this] into a JSON-safe object that can be converted back to a
  /// [SuitePlatform] using [new SuitePlatform.deserialize].
  Object serialize() => {'platform': platform.serialize(), 'os': os.identifier};
}
