# See https://pub.dev/packages/mono_repo

sdk:
- pubspec
- stable # We will want to hardcode 2.19 once 3.x comes out

stages:
- analyze_and_format:
  - group:
    - format
    - analyze: --fatal-infos
    sdk:
    - pubspec
- unit_test:
  - test: -p chrome,vm,node
    os:
    - linux
    - windows
