# Dependabot configuration file.
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - autosubmit
    groups:
      github-actions:
        patterns:
          - "*"

  # Check daily for major version dependency updates for packages which depend
  # on package:analyzer.
  - package-ecosystem: "pub"
    directory: "pkgs/test"
    schedule:
      interval: "daily"
    versioning-strategy: increase-if-necessary
    reviewers:
      - "natebosch"
  - package-ecosystem: "pub"
    directory: "pkgs/test_core"
    schedule:
      interval: "daily"
    versioning-strategy: increase-if-necessary
    reviewers:
      - "natebosch"
