include: package:dart_flutter_team_lints/analysis_options.yaml

linter:
  rules:
    - avoid_private_typedef_functions
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_runtimeType_toString
    - unnecessary_await_in_return
