include: package:pedantic/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    # There are a number of deprecated members used through this package
    deprecated_member_use_from_same_package: ignore
    unsafe_html: ignore
  enable-experiment:
    - non-nullable
linter:
  rules:
    - avoid_private_typedef_functions
    - await_only_futures
    - implementation_imports
    - prefer_generic_function_type_aliases
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - unnecessary_const
    - unnecessary_new
