include: package:dart_flutter_team_lints/analysis_options.yaml
analyzer:
  language:
    strict-casts: true
  errors:
    # There are a number of deprecated members used through this package
    deprecated_member_use_from_same_package: ignore
    unsafe_html: ignore
    type_annotate_public_apis: ignore
    lines_longer_than_80_chars: ignore
    only_throw_errors: ignore

linter:
  rules:
    - avoid_private_typedef_functions
    - prefer_expression_function_bodies
