analyzer:
  strong-mode: true
# Upgrade lints to errors that will break Google3
errors:
  unused_element: error
  unused_import: error
  unused_local_variable: error
  dead_code: error
  ### Useful to uncomment during development to remove the noise of the many
  ### deprecated APIs.
  # deprecated_member_use: ignore
linter:
  rules:
    - await_only_futures
    - implementation_imports
