stages:
    - analyze_and_format:
      - group:
        - dartfmt: sdk
        - dartanalyzer: --fatal-infos --fatal-warnings .
        dart: dev
      - group:
        - dartanalyzer: --fatal-warnings .
        dart: 2.4.0
    - unit_test:
      - group:
        - test: --preset travis
        dart: dev
