# See https://pub.dev/packages/mono_repo

sdk:
- dev
- 2.18.0-165.1.beta

stages:
- analyze_and_format:
  - group:
    - format
    - analyze: --fatal-infos
    sdk:
    - dev
- unit_test:
  - group:
    - command: dart test --preset travis -x browser
      os:
      - linux
      - windows
