dart:
  - dev

stages:
  - analyze_and_format:
    - group:
      - dartfmt: sdk
      - dartanalyzer: --enable-experiment=non-nullable --fatal-infos --fatal-warnings .
  - unit_test:
    - group:
      - command: pub run --enable-experiment=non-nullable test --preset travis -x browser
