dart:
  - dev

stages:
  - analyze_and_format:
    - group:
      - dartfmt: sdk
      - dartanalyzer: --fatal-infos --fatal-warnings .
  - unit_test:
    - group:
      - command: pub run test --preset travis -x browser
