# See https://pub.dev/packages/mono_repo

sdk:
- dev
- pubspec

stages:
- analyze_and_format:
  - group:
    - format
    - analyze: --fatal-infos
    sdk:
    - dev
- unit_test:
  - group:
    - command: dart test -p vm,chrome -c dart2js,dart2wasm,exe,kernel,source
      os:
      - linux
      - windows
