// Copyright (c) 2024, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:test/src/runner/browser/compilers/boostrap_content.dart';
import 'package:test/test.dart';

void main() {
  group('generateNodeBootstrapContent', () {
    test('generates expected output', () {
      final bootstrapContent = generateDart2WasmBootstrapContent(
        testUri: Uri.parse('file:///absolute/path/to/test/my_test.dart'),
        languageVersionComment: '',
      );
      expect(
        bootstrapContent,
        '''
        
        import "package:test/src/bootstrap/node.dart";

        import 'file:///absolute/path/to/test/my_test.dart' as test;

        void main() {
          internalBootstrapNodeTest(() => test.main);
        }
      ''',
      );
    });

    test('contains test URI import with "test" prefix', () {
      final bootstrapContent = generateDart2WasmBootstrapContent(
        testUri: Uri.parse('file:///absolute/path/to/test/my_test.dart'),
        languageVersionComment: '',
      );
      expect(
        bootstrapContent,
        contains(
          "import 'file:///absolute/path/to/test/my_test.dart' as test;",
        ),
        reason:
            'The test bootstrap content must contain an import of the test URI '
            'with the prefix "test". Dart DevTools depends on logic that '
            'searches for a prefix named "test" to find the URI of the Dart '
            'library under test. The "test" prefix matches the prefix '
            'generated by Flutter tools.',
      );
    });
  });
}
