# See https://pub.dev/packages/mono_repo

sdk:
- pubspec

stages:
- analyze_and_format:
  - group:
    - format
    - analyze: --fatal-infos
    sdk:
    - stable
- unit_test:
  - test: -p chrome,vm,node
    os:
    - linux
    - windows
