# See https://pub.dev/packages/mono_repo

sdk:
- main

stages:
- analyze_and_format:
  - group:
    - format
    - analyze: --fatal-infos
- unit_test:
  - group:
    - command: sudo apt-get install google-chrome-beta && which google-chrome-beta
    - test:
      os:
      - linux
