# See https://pub.dev/packages/mono_repo

sdk:
- pubspec
- dev

os:
- linux
- windows

stages:
- analyze_and_format:
  - group:
    - format
    - analyze: --fatal-infos
- unit_test:
  # The config here is a regression test for https://github.com/dart-lang/test/issues/2006
  - test: --timeout=60s
