name: wasm_tests
publish_to: none
environment:
  sdk: ^3.1.0
dev_dependencies:
  dart_flutter_team_lints: ^2.1.1
  test: any
dependency_overrides:
  test:
    path: ../../pkgs/test
  test_api:
    path: ../../pkgs/test_api
  test_core:
    path: ../../pkgs/test_core
