name: regression_tests
publish_to: none
environment:
  sdk: ^3.2.0
dependencies:
  test: any
dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
dependency_overrides:
  test:
    path: ../../pkgs/test
  test_api:
    path: ../../pkgs/test_api
  test_core:
    path: ../../pkgs/test_core
