name: spectate
version: 0.1.0-wip
description: >-
  Utilities to spy on function calls, prints, and process exit.
repository: https://github.com/dart-lang/test/tree/master/pkgs/spectate
issue_tracker: https://github.com/dart-lang/test/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Aspectate

resolution: workspace

environment:
  sdk: ^3.11.0

dev_dependencies:
  checks: ^0.4.0-wip
  test: ^1.32.0-wip
