# See https://pub.dev/packages/mono_repo

sdk:
- 2.18.0
- stable # Will be replaced with 2.19 once 3.0 comes out

stages:
- analyze_and_format:
  - group:
    - format
    - analyze: --fatal-infos
    sdk:
    - stable
- unit_test:
  - test: -p chrome,vm,node
    os:
    - linux
    - windows
