dart:
  - dev
  - stable

stages:
    - analyze_and_format:
      - group:
        - format
        - analyze: --fatal-infos --fatal-warnings .
        dart:
        - dev
    - unit_test:
      - test: -p chrome,vm,node
        os:
        - linux
        - windows
