# See https://pub.dev/packages/mono_repo

sdk:
- dev
- 2.18.0

stages:
- analyze_and_format:
  - group:
    - format
    - analyze: --fatal-infos
    sdk:
    - dev
- unit_test:
  - test: -p chrome,vm,node
    os:
    - linux
    - windows
