# Created with package:mono_repo v6.7.2
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions:
  contents: read

jobs:
  job_001:
    name: "unit_test; `dart test -p chrome,vm -c dart2js,exe -r expanded --suite-load-timeout=15s`"
    runs-on: windows-latest
    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - id: integration_tests_cross_compiler_hang_pub_upgrade
        name: integration_tests/cross_compiler_hang; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: integration_tests/cross_compiler_hang
      - name: "integration_tests/cross_compiler_hang; dart test -p chrome,vm -c dart2js,exe -r expanded --suite-load-timeout=15s"
        run: "dart test -p chrome,vm -c dart2js,exe -r expanded --suite-load-timeout=15s"
        if: "always() && steps.integration_tests_cross_compiler_hang_pub_upgrade.conclusion == 'success'"
        working-directory: integration_tests/cross_compiler_hang
  job_002:
    name: Notify failure
    runs-on: ubuntu-latest
    if: "(github.event_name == 'push' || github.event_name == 'schedule') && failure()"
    steps:
      - run: |
          curl -H "Content-Type: application/json" -X POST -d \
            "{'text':'Build failed! ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}'}" \
            "${CHAT_WEBHOOK_URL}"
        env:
          CHAT_WEBHOOK_URL: "${{ secrets.BUILD_AND_TEST_TEAM_CHAT_WEBHOOK_URL }}"
    needs:
      - job_001
